spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/careerosx
spring.datasource.username=careerosx
spring.datasource.password=careerosx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true